version: 2.1
jobs:
  run-tests:
    docker:
      - image: circleci/ruby:2.5.7-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems-v2-{{ checksum "Gemfile" }}
            - gems-v2-
      - run: bundle check || bundle install
      - save_cache:
          key: gems-v2--{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake spec

workflows:
  tests:
    jobs:
      - run-tests
