version: 2.1

workflows:
  tests:
    jobs:
      - run-tests
  snyk:
    jobs:
      - run-tests
      - snyk:
          # Must define SNYK_TOKEN env
          context: snyk-env 
          requires: 
            - run-tests
      - publish:
          requires:
            - run-tests
          context:
            - gemfury
          filters:
            # only publish gem after cutting tag
            tags:
              only: /.*/
            branches:
              ignore: /.*/

jobs:
  run-tests:
    docker:
      - image: circleci/ruby:2.4.6-jessie
    steps:
      - checkout
      - restore_cache:
          keys:
            - gems-v2-{{ checksum "Gemfile.lock" }}
            - gems-v2-
      - run: bundle check || bundle config set --local path 'vendor/bundle'
      - persist_to_workspace:
          root: .
          paths:
            - Gemfile
            - Gemfile.lock
            - .snyk
      - save_cache:
          key: gems-v2--{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      #- run: bundle exec rake spec
  snyk:
    docker:
      - image: snyk/snyk-cli:rubygems
    steps:
      - attach_workspace:
          at: .
      - run: snyk test
      - run:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]
            then
            snyk monitor --org=auth0-sdks
            fi
          when: always
  publish:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - run:
          name: Build and publish gem to gemfury
          command: ./.circleci/publish.sh
          

